name: Sphinx build

on: push


env:
  app: Accept:application/vnd.github.v3+json


jobs:
  repocheck:
    name: Check if repos are up to date
    runs-on: ubuntu-20.04

    outputs:
      current: ${{ steps.check.outputs.current }}

    steps:
      - name: Fetch check run ids
        id: fetch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/actions/runs/{run_id}/jobs
          repo: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo check run ids
        run: echo "job ids - ${{ toJSON(fromJSON(steps.fetch.outputs.data).jobs.*.id) }}

#       cd ${{ github.workspace }}/tests/ci
 #       jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$helper_id/jobs
 #       conclusion=$(echo $jobs_url | ./check_status.py completion "Repo check")
 #       if [[ $conclusion == "failure" ]]; then
 #         exit 1
 #       fi
 #   - uses: actions/cache@v2
 #     with:
 #       path: ~/repocheck_file
 #       key: repocheck-${{ github.run_id }}
       
        
