name: Sphinx build

on: push


env:
  app: Accept:application/vnd.github.v3+json


jobs:
  repocheck:
    name: Check if repos are up to date
    runs-on: ubuntu-20.04

    outputs:
      current: ${{ steps.check.outputs.current }}

    steps:
    - uses: actions/checkout@v2

    - name: Wait for caching source
      run: sleep 30

    - uses: actions/cache@v2
      with:
        path: ~/id_file
        key: helperid-${{ github.run_id }}
